/**
 * Loads the OSM-derived demo route set and the demo school location.
 *
 * INTEGRITY: demoRoutes.json was generated by scripts/fetchOsmRoutes.mjs from REAL
 * routing output of the public OSRM demo server (OSM data). Every route therefore
 * carries source 'osm-derived'. Road classes and density features remain
 * hand-authored ASSUMED proxies (see the script header); only the geometry,
 * lengths, corridor distances and turn counts are measured. School coordinates are
 * approximate (the contract's `approximateLocation: true` says so in the UI).
 */

import raw from '../fixtures/demoRoutes.json';
import { haversineM, segmentMidpoint } from '../geo';
import { validationErrors } from './validate';
import type { Route, Segment } from '@/contracts';

interface DemoRoutesFile {
  _comment: string;
  schoolArea: { name: string; lat: number; lon: number };
  routes: Route[];
}

const file = raw as unknown as DemoRoutesFile;

/**
 * Structural issues found at import time. Exported so the UI can surface a
 * developer warning rather than silently rendering broken geometry. Empty array =
 * the shipped fixture satisfies every contract invariant.
 */
export const DEMO_ROUTE_ISSUES: string[] = validationErrors(file.routes);

export const DEMO_ROUTES: Route[] = file.routes;

/** Unique segments across all demo routes, de-duplicated by id. */
export function demoUniqueSegments(routes: Route[] = DEMO_ROUTES): Segment[] {
  const seen = new Map<string, Segment>();
  for (const route of routes) {
    for (const seg of route.segments) {
      if (!seen.has(seg.id)) seen.set(seg.id, seg);
    }
  }
  return [...seen.values()];
}

export interface DemoSchool {
  name: string;
  segment: Segment;
  approximateLocation: boolean;
}

let cachedSchool: DemoSchool | null = null;

/**
 * The demo school is anchored to a real segment of the demo network: the segment
 * whose midpoint is nearest the school area coordinate, preferring walkable
 * classes but preferring PROXIMITY overall. Rationale: the school window scores
 * exposure AT the school, so a residential street 65 m away is more representative
 * than a footway 1.5 km away. That keeps the school on the map geometry instead of
 * floating as an orphan pin.
 */
const SCHOOL_CLASS_PREFERENCE = [
  'footway',
  'path',
  'residential',
  'tertiary',
  'secondary',
  'primary',
  'trunk',
];

export function demoSchool(): DemoSchool {
  if (cachedSchool) return cachedSchool;

  const target = { lat: file.schoolArea.lat, lon: file.schoolArea.lon };
  const score = (seg: Segment): number => {
    const rank = SCHOOL_CLASS_PREFERENCE.indexOf(seg.roadClass);
    const d = haversineM(segmentMidpoint(seg), target);
    // Within 150 m, a walkable class wins ties; beyond that, proximity decides.
    return d < 150 ? rank * 1000 + d : 100000 + d;
  };

  let best: Segment | null = null;
  let bestScore = Number.POSITIVE_INFINITY;

  for (const route of DEMO_ROUTES) {
    for (const seg of route.segments) {
      const s = score(seg);
      if (s < bestScore) {
        bestScore = s;
        best = seg;
      }
    }
  }

  const segment: Segment = best ?? {
    id: 'demo-school',
    roadClass: 'footway',
    lengthM: 120,
    coords: [
      { lat: target.lat, lon: target.lon },
      { lat: target.lat + 0.001, lon: target.lon + 0.001 },
    ],
    features: {
      distToMainRoadM: 60,
      intersectionDensityPer100m: 1,
      trafficSignalsWithin50m: 0,
      busStopsWithin30m: 0,
      greenFraction100m: 0.8,
      buildingDensity: 0.2,
      nearbyRoads: [{ roadClass: 'primary', distanceM: 60 }],
    },
  };

  cachedSchool = {
    name: `${file.schoolArea.name} (approx.)`,
    segment,
    approximateLocation: true,
  };
  return cachedSchool;
}

/** The school area coordinate, for placing a map marker. */
export function demoSchoolLocation(): { lat: number; lon: number } {
  return segmentMidpoint(demoSchool().segment);
}
