/**
 * Loads the hand-authored demo route set and the demo school location.
 *
 * INTEGRITY: demoRoutes.json was generated by scripts/makeDemoRoutes.mjs WITHOUT any
 * OpenStreetMap or OSRM call. Every route therefore carries source 'hand-authored'
 * and the school coordinates are approximate (the contract's
 * `approximateLocation: true` says so in the UI).
 */

import raw from '../fixtures/demoRoutes.json';
import { haversineM, segmentMidpoint } from '../geo';
import { validationErrors } from './validate';
import type { Route, Segment } from '@/contracts';

interface DemoRoutesFile {
  _comment: string;
  schoolArea: { name: string; lat: number; lon: number };
  routes: Route[];
}

const file = raw as unknown as DemoRoutesFile;

/**
 * Structural issues found at import time. Exported so the UI can surface a
 * developer warning rather than silently rendering broken geometry. Empty array =
 * the shipped fixture satisfies every contract invariant.
 */
export const DEMO_ROUTE_ISSUES: string[] = validationErrors(file.routes);

export const DEMO_ROUTES: Route[] = file.routes;

/** Unique segments across all demo routes, de-duplicated by id. */
export function demoUniqueSegments(routes: Route[] = DEMO_ROUTES): Segment[] {
  const seen = new Map<string, Segment>();
  for (const route of routes) {
    for (const seg of route.segments) {
      if (!seen.has(seg.id)) seen.set(seg.id, seg);
    }
  }
  return [...seen.values()];
}

export interface DemoSchool {
  name: string;
  segment: Segment;
  approximateLocation: boolean;
}

let cachedSchool: DemoSchool | null = null;

/**
 * The demo school is anchored to a real segment of the demo network: we pick the
 * park-route segment whose midpoint is nearest the school area coordinate. That
 * keeps the school on the map geometry instead of floating as an orphan pin.
 */
export function demoSchool(): DemoSchool {
  if (cachedSchool) return cachedSchool;

  const target = { lat: file.schoolArea.lat, lon: file.schoolArea.lon };
  let best: Segment | null = null;
  let bestDist = Number.POSITIVE_INFINITY;

  for (const route of DEMO_ROUTES) {
    for (const seg of route.segments) {
      // Prefer walkable classes; the school gate is on a footway, not a trunk road.
      if (seg.roadClass !== 'footway' && seg.roadClass !== 'path') continue;
      const mid = segmentMidpoint(seg);
      const d = haversineM(mid, target);
      if (d < bestDist) {
        bestDist = d;
        best = seg;
      }
    }
  }

  const segment: Segment = best ?? {
    id: 'demo-school',
    roadClass: 'footway',
    lengthM: 120,
    coords: [
      { lat: target.lat, lon: target.lon },
      { lat: target.lat + 0.001, lon: target.lon + 0.001 },
    ],
    features: {
      distToMainRoadM: 60,
      intersectionDensityPer100m: 1,
      trafficSignalsWithin50m: 0,
      busStopsWithin30m: 0,
      greenFraction100m: 0.8,
      buildingDensity: 0.2,
      nearbyRoads: [{ roadClass: 'primary', distanceM: 60 }],
    },
  };

  cachedSchool = {
    name: `${file.schoolArea.name} (approx.)`,
    segment,
    approximateLocation: true,
  };
  return cachedSchool;
}

/** The school area coordinate, for placing a map marker. */
export function demoSchoolLocation(): { lat: number; lon: number } {
  return segmentMidpoint(demoSchool().segment);
}
