/**
 * ============================================================================
 * SIMULATED DEMO OBSERVATIONS
 * ============================================================================
 *
 * ##### EVERY ITEM HERE IS SIMULATED. NONE OF IT IS A REAL OBSERVATION. #####
 *
 * All 30 seeds carry `isSimulated: true`, are generated by a seeded RNG (never
 * Math.random) and are rendered in the UI with a "SIM" badge behind a "Show
 * simulated demo pins" toggle. They exist so the evidence layer is visible in a
 * 3-minute demo; they are not evidence of anything and must never be described as
 * measurements, crowd reports from real people, or validation data.
 *
 * They are NOT station data and are never used by the backtest.
 */

import { addHours } from '../time';
import { mulberry32, uniform } from '../rng';
import type { Observation, PhotoObservation, ReportObservation } from '@/contracts';

/** Exactly this many seeds are produced. */
export const SEED_COUNT = 30;
const PHOTO_COUNT = 24;
const REPORT_COUNT = 6;

/**
 * Clusters are placed along the demo corridor. Coordinates are jittered
 * deterministically around each cluster centre. These positions are HAND-AUTHORED
 * approximations, not GPS fixes from real contributors.
 */
interface Cluster {
  lat: number;
  lon: number;
  spreadM: number;
  /** tauOpt centre — higher on the main road, lower in the park. ASSUMED. */
  tauCentre: number;
}

const CLUSTERS: Cluster[] = [
  // Main road corridor: heaviest simulated haze.
  { lat: 27.6735, lon: 85.3105, spreadM: 60, tauCentre: 0.55 },
  { lat: 27.6698, lon: 85.3148, spreadM: 70, tauCentre: 0.62 },
  { lat: 27.666, lon: 85.3188, spreadM: 65, tauCentre: 0.5 },
  // Residential grid: moderate.
  { lat: 27.671, lon: 85.3088, spreadM: 80, tauCentre: 0.3 },
  // Park / open ground: lightest.
  { lat: 27.6642, lon: 85.3122, spreadM: 90, tauCentre: 0.16 },
  { lat: 27.6618, lon: 85.3215, spreadM: 75, tauCentre: 0.2 },
];

const REPORTS: Array<{ report: ReportObservation['report']; cluster: number }> = [
  { report: 'smoky', cluster: 0 },
  { report: 'smoky', cluster: 1 },
  { report: 'dusty', cluster: 3 },
  { report: 'clear', cluster: 4 },
  { report: 'smoky', cluster: 5 },
  { report: 'clear', cluster: 2 },
];

const METRES_PER_DEG_LAT = 111_320;

/** Offset a cluster centre by a random walk of up to `spreadM`, deterministically. */
function jitter(cluster: Cluster, rnd: () => number): { lat: number; lon: number } {
  const dLat = uniform(rnd, -cluster.spreadM, cluster.spreadM) / METRES_PER_DEG_LAT;
  const dLon = uniform(rnd, -cluster.spreadM, cluster.spreadM) / (METRES_PER_DEG_LAT * 0.886);
  return { lat: cluster.lat + dLat, lon: cluster.lon + dLon };
}

/**
 * Build the simulated seed set, all within the last 6 hours of `anchorISO`.
 * Deterministic: the same anchor hour always yields the same 30 observations.
 */
export function seedObservations(anchorISO: string): Observation[] {
  const anchorMs = Date.parse(anchorISO);
  const safeAnchor = Number.isFinite(anchorMs) ? anchorMs : 0;
  const seed = Math.floor(safeAnchor / 3_600_000);
  const rnd = mulberry32(seed ^ 0x5eed);

  const out: Observation[] = [];

  for (let i = 0; i < PHOTO_COUNT; i++) {
    const cluster = CLUSTERS[i % CLUSTERS.length];
    const pos = jitter(cluster, rnd);

    // Spread over the last 6 h, so the time-decay kernel has something to bite on.
    const minutesAgo = uniform(rnd, 5, 360);
    const timeISO = addHours(anchorISO, -minutesAgo / 60);

    const photo: PhotoObservation = {
      id: `sim-photo-${String(i + 1).padStart(2, '0')}`,
      kind: 'photo',
      lat: pos.lat,
      lon: pos.lon,
      timeISO,
      isSimulated: true,
      // ASSUMED optical depths, shaped to be higher near the main road.
      tauOpt: Math.round(Math.max(0.03, cluster.tauCentre + uniform(rnd, -0.09, 0.09)) * 1000) / 1000,
      // ASSUMED humidity, in the 0..1 contract range.
      rh01: Math.round(uniform(rnd, 0.45, 0.85) * 1000) / 1000,
      scene: rnd() < 0.35 ? 'canyon' : 'open',
      note: 'SIMULATED demo seed — not a real photograph.',
    };
    out.push(photo);
  }

  for (let i = 0; i < REPORT_COUNT; i++) {
    const spec = REPORTS[i];
    const cluster = CLUSTERS[spec.cluster];
    const pos = jitter(cluster, rnd);
    const minutesAgo = uniform(rnd, 5, 360);

    const report: ReportObservation = {
      id: `sim-report-${String(i + 1).padStart(2, '0')}`,
      kind: 'report',
      report: spec.report,
      lat: pos.lat,
      lon: pos.lon,
      timeISO: addHours(anchorISO, -minutesAgo / 60),
      isSimulated: true,
      note: 'SIMULATED demo seed — not a real crowd report.',
    };
    out.push(report);
  }

  return out;
}
